import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';
import * as moment from 'moment';

import { FormControl, Validators } from '@angular/forms';


@Component({
  selector: 'app-apod',
  templateUrl: './apod.component.html',
  styleUrls: ['./apod.component.css']
})
export class ApodComponent implements OnInit {

  
  
  constructor() { }

  posts = [{"copyright":"Petr Horalek","date":"2021-01-01","explanation":"The South Celestial Pole is easy to spot in star trail images of the southern sky. The extension of Earth's axis of rotation to the south, it's at the center of all the southern star trail arcs. In this starry panorama streching about 60 degrees across deep southern skies the South Celestial Pole is somewhere near the middle though, flanked by bright galaxies and southern celestial gems. Across the top of the frame are the stars and nebulae along the plane of our own Milky Way Galaxy. Gamma Crucis, a yellowish giant star heads the Southern Cross near top center, with the dark expanse of the Coalsack nebula tucked under the cross arm on the left. Eta Carinae and the reddish glow of the Great Carina Nebula shine along the galactic plane near the right edge. At the bottom are the Large and Small Magellanic clouds, external galaxies in their own right and satellites of the mighty Milky Way. A line from Gamma Crucis through the blue star at the bottom of the southern cross, Alpha Crucis, points toward the South Celestial Pole, but where exactly is it? Just look for south pole star Sigma Octantis. Analog to Polaris the north pole star, Sigma Octantis is little over one degree fom the the South Celestial pole.","hdurl":"https://apod.nasa.gov/apod/image/2101/2020_12_16_Kujal_Jizni_Pol_1500px-3.png","media_type":"image","service_version":"v1","title":"Galaxies and the South Celestial Pole","url":"https://apod.nasa.gov/apod/image/2101/2020_12_16_Kujal_Jizni_Pol_1500px-3.jpg"},

  {"copyright":"Mike Smolinsky","date":"2021-01-02","explanation":"In the mid 19th century, one of the first photographic technologies used to record the lunar surface was the wet-plate collodion process, notably employed by British astronomer Warren De la Rue. To capture an image, a thick, transparent mixture was used to coat a glass plate, sensitized with silver nitrate, exposed at the telescope, and then developed to create a negative image on the plate. To maintain photographic sensitivity, the entire process, from coating to exposure to developing, had to be completed before the plate dried, in a span of about 10 to 15 minutes. This modern version of a wet-plate collodion image celebrates lunar photography's early days, reproducing the process using modern chemicals to coat a glass plate from a 21st century hardware store. Captured last November 28 with an 8x10 view camera and backyard telescope, it faithfully records large craters, bright rays, and dark, smooth mare of the waxing gibbous Moon. Subsequently digitized, the image on the plate was 8.5 centimeters in diameter and exposed while tracking for 2 minutes. The wet plate's effective photographic sensitivity was about ISO 1.  In your smart phone, the camera sensor probably has a photographic sensitivity range of ISO 100 to 6400 (and needs to be kept dry ...).","hdurl":"https://apod.nasa.gov/apod/image/2101/WetCollodionLunar112820SMO.jpg","media_type":"image","service_version":"v1","title":"21st Century Wet Collodion Moon","url":"https://apod.nasa.gov/apod/image/2101/WetCollodionLunar112820SMO_1024.jpg"},
  
  {"copyright":"Hallgrimur P. Helgason Rollover Annotation: Judy Schmidt","date":"2021-01-03","explanation":"All of the other aurora watchers had gone home. By 3:30 am in Iceland, on a quiet September night, much of that night's auroras had died down. Suddenly, unexpectedly, a new burst of particles streamed down from space, lighting up the Earth's atmosphere once again. This time, surprisingly, pareidoliacally, the night lit up with an  amazing shape reminiscent of a giant phoenix. With camera equipment at the ready, two quick sky images were taken, followed immediately by a third of the land.  The mountain in the background is Helgafell, while the small foreground river is called Kald\u00e1, both located about 30 kilometers north of Iceland's capital Reykjav\u00edk. Seasoned skywatchers will note that just above the mountain, toward the left, is the constellation of Orion, while the Pleiades star cluster is also visible just above the frame center.  The 2016 aurora, which lasted only a minute and was soon gone forever --  would possibly be dismissed as an fanciful fable -- were it not captured in the featured, digitally-composed, image mosaic.    Almost Hyperspace: Random APOD Generator","hdurl":"https://apod.nasa.gov/apod/image/2101/PhoenixAurora_Helgason_3130.jpg","media_type":"image","service_version":"v1","title":"A Phoenix Aurora over Iceland","url":"https://apod.nasa.gov/apod/image/2101/PhoenixAurora_Helgason_960.jpg"},
  
  {"copyright":"Thomas Ashcraft","date":"2021-01-04","explanation":"What causes sprite lightning? Mysterious bursts of light in the sky that momentarily resemble gigantic jellyfish have been recorded for over 30 years, but apart from a general association with positive cloud-to-ground lightning, their root cause remains unknown. Some thunderstorms have them -- most don't.  Recently, however, high speed videos are better detailing how sprites actually develop.  The featured video, captured in mid-2019, is fast enough -- at about 100,000 frames per second -- to time-resolve several sprite \"bombs\" dropping and developing into the multi-pronged streamers that appear on still images. Unfortunately, the visual clues provided by videos like these do not fully resolve the sprite origins mystery. High speed vidoes do indicate to some researchers, though, that sprites are more likely to occur when plasma irregularities exist in the upper atmosphere.    Astrophysicists: Browse 2,300+ codes in the Astrophysics Source Code Library","media_type":"video","service_version":"v1","title":"Sprite Lightning at 100,000 Frames Per Second","url":"https://www.youtube.com/embed/zS_XgF9i8tc?rel=0"},
  
  {"copyright":"Jos\u00e9 Mtanous","date":"2021-01-05","explanation":"What is the Small Magellanic Cloud? It has turned out to be a galaxy.  People who have wondered about this little fuzzy patch in the southern sky included Portuguese navigator Ferdinand Magellan and his crew, who had plenty of time to study the unfamiliar night sky of the south during the first circumnavigation of planet Earth in the early 1500s. As a result, two celestial wonders easily visible for southern hemisphere skygazers are now known in Western culture as the Clouds of Magellan. Within the past 100 years, research has shown that these cosmic clouds are dwarf irregular galaxies, satellites of our larger spiral Milky Way Galaxy. The Small Magellanic Cloud actually spans 15,000 light-years or so and contains several hundred million stars. About 210,000 light-years away in the constellation of the Tucan (Tucana), it is more distant than other known Milky Way satellite galaxies, including the Sagittarius Dwarf galaxy and the Large Magellanic Cloud. This sharp image also includes the foreground globular star cluster 47 Tucanae on the right.","hdurl":"https://apod.nasa.gov/apod/image/2101/SMC_Mtanous_4464.jpg","media_type":"image","service_version":"v1","title":"The Small Cloud of Magellan","url":"https://apod.nasa.gov/apod/image/2101/SMC_Mtanous_960.jpg"},
  
  {"date":"2021-01-06","explanation":"Why are these sand dunes on Mars striped?  No one is sure.  The featured image shows striped dunes in Kunowsky Crater on Mars, photographed recently with the Mars Reconnaissance Orbiter\u2019s HiRISE Camera.  Many Martian dunes are known to be covered unevenly with carbon dioxide (dry ice) frost, creating patterns of light and dark areas.  Carbon dioxide doesn\u2019t melt, but sublimates, turning directly into a gas. Carbon dioxide is also a greenhouse material even as a solid, so it can trap heat under the ice and sublimate from the bottom up, causing geyser-like eruptions.  During Martian spring, these eruptions can cause a pattern of dark defrosting spots, where the darker sand is exposed.  The featured image, though, was taken during Martian autumn, when the weather is getting colder \u2013 making these stripes particularly puzzling.  One hypothesis is that they are caused by cracks in the ice that form from weaker eruptions or thermal stress as part of the day-night cycle, but research continues.  Watching these dunes and others through more Martian seasons may give us more clues to solve this mystery.","hdurl":"https://apod.nasa.gov/apod/image/2101/StripedDunes_HiRISE_1182.jpg","media_type":"image","service_version":"v1","title":"Striped Sand Dunes on Mars","url":"https://apod.nasa.gov/apod/image/2101/StripedDunes_HiRISE_1080.jpg"},
  
  {"copyright":"Miloslav Druckmuller","date":"2021-01-07","explanation":"Along a narrow path crossing southern South America through Chile and Argentina, the final New Moon of 2020 moved in front of the Sun on December 14 in the year's only total solar eclipse. Within about 2 days of perigee, the closest point in its elliptical orbit, the New Moon's surface is faintly lit by earthshine in this dramatic composite view. The image is a processed composite of 55 calibrated exposures ranging from 1/640 to 3 seconds. Covering a large range in brightness during totality, it reveals the dim lunar surface and faint background stars, along with planet-sized prominences at the Sun's edge, an enormous coronal mass ejection, and sweeping coronal structures normally hidden in the Sun's glare. Look closely for an ill-fated sungrazing Kreutz family comet (C/2020 X3 SOHO) approaching from the lower left, at about the 7 o'clock position. In 2021 eclipse chasers will see an annular solar eclipse coming up on June 10. They'll have to wait until December 4 for the only total solar eclipse in 2021 though. That eclipse will be total along a narrow path crossing the southernmost continent of Antarctica.","hdurl":"https://apod.nasa.gov/apod/image/2101/Tse_2020_400mm_dmwa-rot.png","media_type":"image","service_version":"v1","title":"Total Solar Eclipse 2020","url":"https://apod.nasa.gov/apod/image/2101/Tse_2020_400mm_dmwa-rot.jpg"},
  
  {"copyright":"island universe","date":"2021-01-08","explanation":"Barred spiral galaxy NGC 1365 is truly a majestic island universe some 200,000 light-years across. Located a mere 60 million light-years away toward the chemical constellation Fornax, NGC 1365 is a dominant member of the well-studied Fornax Cluster of galaxies. This impressively sharp color image shows the intense, reddish star forming regions near the ends of central bar and along the spiral arms, with details of the obscuring dust lanes cutting across the galaxy's bright core. At the core lies a supermassive black hole. Astronomers think NGC 1365's prominent bar plays a crucial role in the galaxy's evolution, drawing gas and dust into a star-forming maelstrom and ultimately feeding material into the central black hole.","hdurl":"https://apod.nasa.gov/apod/image/2101/NGC-1365-RGB-19-DEC-2020_Leo_Mike.jpg","media_type":"image","service_version":"v1","title":"NGC 1365: Majestic Island Universe","url":"https://apod.nasa.gov/apod/image/2101/NGC-1365-RGB-19-DEC-2020_Leo_Mike_1024.jpg"},
  
  {"date":"2021-01-09","explanation":"Like Earth's moon, Saturn's largest moon Titan is locked in synchronous rotation. This mosaic of images recorded by the Cassini spacecraft in May of 2012 shows its anti-Saturn side, the side always facing away from the ringed gas giant. The only moon in the solar system with a dense atmosphere, Titan is the only solar system world besides Earth known to have standing bodies of liquid on its surface and an earthlike cycle of liquid rain and evaporation. Its high altitude layer of atmospheric haze is evident in the Cassini view of the 5,000 kilometer diameter moon over Saturn's rings and cloud tops. Near center is the dark dune-filled region known as Shangri-La. The Cassini-delivered Huygens probe rests below and left of center, after the most distant landing for a spacecraft from Earth.","hdurl":"https://apod.nasa.gov/apod/image/2101/PIA19642Titan.jpg","media_type":"image","service_version":"v1","title":"Titan: Moon over Saturn","url":"https://apod.nasa.gov/apod/image/2101/PIA19642Titan1024.jpg"},
  
  {"date":"2021-01-10","explanation":"In the center of nearby star-forming region lies a huge cluster containing some of the largest, hottest, and most massive stars known. These stars, known collectively as star cluster R136, part of the Tarantula Nebula, were captured in the featured image in visible light in 2009 through the Hubble Space Telescope. Gas and dust clouds in the Tarantula Nebula, have been sculpted into elongated shapes by powerful winds and ultraviolet radiation from these hot cluster stars.  The Tarantula Nebula lies within a neighboring galaxy known as the Large Magellanic Cloud and is located a mere 170,000 light-years away.","hdurl":"https://apod.nasa.gov/apod/image/2101/30dor_hubble_3939.jpg","media_type":"image","service_version":"v1","title":"Star Cluster R136 Breaks Out","url":"https://apod.nasa.gov/apod/image/2101/30dor_hubble_960.jpg"}]

  ngOnInit(): void {
  
  
  }

  doSomethingOnError(event:any) {
    event.target.src = 'https://apod.nasa.gov/apod/image/2101/30dor_hubble_960.jpg'
}


}
